### ISSUE TITLE
Compile time errors with latest release

### ISSUE THREAD

**Issue by rdmark** [christopherkobayashi/netatalk-classic#1]
With the latest release, 20200923, as well as the latest netatalk-classic code, the code won't commit in my environment. This seems to have broken after the 20200806 release, which compiles fine for me.
Raspberry Pi 3B, up to date Raspberry Pi OS (Debian based)

./configure --enable-debian --enable-cups --sysconfdir=/etc --with-uams-path=/usr/lib/netatalk

$ gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

```
asingle.c: In function ‘single_read’:
asingle.c:408:79: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘ssize_t’ {aka ‘int’} [-Werror=format=]
  fprintf(stderr, "single_read: Trying to read past end of fork!, ade_len == %lu\n", single.entry[entry_id].ade_len);
                                                                             ~~^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                             %u

```

If I comment out this piece of the code, the next compile time error is:

```
catsearch.c: In function ‘catsearch_afp.isra.3’:
catsearch.c:1095:7: error: ‘uname’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
       catsearch_db(vol, vol->v_root, uname, rmatches,
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      &catpos[0], rbuf + 24, &nrecs, &rsize,
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ext);
      ~~~~
```

I'm not a C coder, so don't have the know-how to address these myself.

**Comment by josch1710** [comment]
Yes, I have that, too. It seems the code assumes, it gets compiled on 64bit systems. There is some code like "x << 32" where x is not bigger than 32 bit, so the compiler complains and exits.

**Comment by christopherkobayashi** [comment]
Hmmm, interesting, I'm not getting issue notifications from GitHub.  Sorry about the delay in reply.

I'll spin up a 32-bit VM and deal with the lossage.

Thanks for letting me know.

**Comment by christopherkobayashi** [comment]
I've added a few gratuitous casts to silence the compile errors.  This isn't optimal, but the offending code are debug fprintf()s, so there is no downside to this scheme.

@josch1710 I'll go through the code soon looking for operations that assume 32-bitness.  Ideally, all of the wire datastructures should be using explicit type sizes instead of short/int/long, with the higher-level stuff using regular types.  Not much attention was paid to that issue by the original authors of netatalk, so I suspect this will be a long slog.

Closing, with thanks.
